#!/bin/bash
VDB_DIR=/var/db/pkg
count() {
    echo ${1} $(grep -l ${1} ${VDB_DIR}/*/*/REPOSITORY | wc -l)
}

for i in $(cave print-repositories | grep -Ev '(installed|layman|repository)'); do
    count ${i}
done
